name: artifact
on:
  workflow_dispatch:
    inputs:
      ZIP_SOURCE_PATH:
        description: " Put source path of zip file"
        default: /home/
        required: true
jobs:
  artifact:
    runs-on: ubuntu-latest
    env:
      ZIP_SOURCE_PATH: ${{ inputs.ZIP_SOURCE_PATH }}
      steps:
      - name: print name
        run: |
              echo $ZIP_SOURCE_PATH
